#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gta2xlwifi

PRODUCT_COPY_FILES += \
    vendor/samsung/gta2xlwifi/proprietary/vendor/app/mcRegistry/07010000000000000000000000000000.tlbin:$(TARGET_COPY_OUT_VENDOR)/app/mcRegistry/07010000000000000000000000000000.tlbin \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/General_cal.acdb \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/Global_cal.acdb \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/Handset_cal.acdb \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/Hdmi_cal.acdb \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/Headset_cal.acdb \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/Speaker_cal.acdb \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/cacert_location.pem:$(TARGET_COPY_OUT_VENDOR)/etc/cacert_location.pem \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/N05QL_s5k5e3yx_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/N05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/P08QL_s5k4h5yc_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/P08QL_s5k4h5yc_module_info.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/Q08QL_s5k4h5yc_module_info.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/Q08QL_s5k4h5yc_module_info.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/s5k4h5yc_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4h5yc_chromatix.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/s5k4h5yc_dw9807_chromatix_gta2s.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k4h5yc_dw9807_chromatix_gta2s.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/s5k5e3yx_f2_2_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/s5k5e3yx_f2_2_chromatix.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/camera/sdm450_camera_gta2xllte.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sdm450_camera_gta2xllte.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/android.hardware.drm-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm-service.widevine.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/android.hardware.gnss@2.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.0-service-qti.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/android.hardware.sensors@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.sensors@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/icd_over_five_vendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/icd_over_five_vendor.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/pa_daemon_qsee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/pa_daemon_qsee.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.dolby.hardware.dms@2.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.dolby.hardware.dms@2.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.trustonic.tee@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.tee@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/init/vendor.trustonic.teeregistry@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.trustonic.teeregistry@1.0-service.rc \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/media_codecs_dolby_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_dolby_audio.xml \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/workspaceFile.qwsp \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/xtra_root_cert.pem:$(TARGET_COPY_OUT_VENDOR)/etc/xtra_root_cert.pem \
    vendor/samsung/gta2xlwifi/proprietary/vendor/etc/yas_set.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/yas_set.cfg \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/Tfa9896.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9896.cnt \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/Tfa9896_invert.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/Tfa9896_invert.cnt \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a225_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pfp.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a225_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a225p5_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a225p5_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a300_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pfp.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a300_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a300_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a330_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pfp.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a330_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a330_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a420_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pfp.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a420_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a420_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_gpmu.fw2 \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pfp.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530v1_pfp.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pfp.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530v1_pm4.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v1_pm4.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530v2_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v2_seq.fw2 \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530v3_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_gpmu.fw2 \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a530v3_seq.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a530v3_seq.fw2 \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a540_gpmu.fw2:$(TARGET_COPY_OUT_VENDOR)/firmware/a540_gpmu.fw2 \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_10_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_10_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_12_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_12_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_1_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_1.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_1_6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_1_6.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_2_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_2_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_4_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_4_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_5_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_5_1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_1.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_5_2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_5_2.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_6_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_6_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/cpp_firmware_v1_8_0.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/cpp_firmware_v1_8_0.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/dbmd8_va_asrp_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd8_va_asrp_fw.bin \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/dbmd8_va_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/dbmd8_va_fw.bin \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/samsung/gta2xlwifi/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw

PRODUCT_PACKAGES += \
    com.qualcomm.qti.ant@1.0 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libQTapGLES \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    android.hardware.gnss@2.0-impl-qti \
    android.hardware.sensors@1.0-impl \
    com.qualcomm.qti.ant@1.0-impl \
    gatekeeper.msm8953 \
    power.qcom \
    thermal.msm8953 \
    vendor.qti.gnss@3.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    vulkan.adreno \
    libC2D2 \
    libCB \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libOpenCL \
    libQSEEComAPI \
    libSecureUILib \
    libStDrvInt \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsp_default_listener \
    libadsprpc \
    libaudcal \
    libbatching \
    libbccQTI \
    libc2d30_bltlib \
    libcdsp_default_listener \
    libcdsprpc \
    libdapparamstorage \
    libdataitems \
    libdiag \
    libdrmtime \
    libdsutils \
    libfastcrc \
    libfastcvadsp_stub \
    libfastcvopt \
    libfloatingfeature \
    libgarden \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libgps.utils \
    libgpustats \
    libgsl \
    libhdr_tm \
    libidl \
    libizat_client_api \
    libizat_core \
    liblbs_core \
    libllvm-glnext \
    libloc_api_v02 \
    libloc_core \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    libmdmdetect \
    libmdsprpc \
    libmmosal_proprietary \
    libmulawdec \
    libpdmapper \
    libperipheral_client \
    libpvr \
    libqdi \
    libqdma_file_agent \
    libqisl \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_encdec \
    libqmiservices \
    librpmb \
    libscalar \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libsdsprpc \
    libsecnativefeature \
    libsecureui \
    libsecureui_svcsock \
    libssd \
    libsynergy_loc_api \
    libsysmon_cdsp_skel \
    libthermalclient \
    libtime_genoff \
    libtinyxml2_1 \
    libxtadapter \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.postproc@1.0 \
    vendor.dolby.hardware.dms@2.0 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0-service \
    vendor.qti.gnss@3.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.tui_comm@1.0 \
    camera.legacy.msm8953 \
    gatekeeper.mdfpp \
    sensors.msm8953 \
    sound_trigger.primary.msm8953 \
    vendor.samsung.hardware.gnss@2.0-impl-sec \
    libMOTION \
    libMcClient \
    libactuator_dw9807 \
    libadm \
    libadpcmdec \
    libchromaflash \
    libchromatix_csidtg_common \
    libchromatix_csidtg_cpp_preview \
    libchromatix_csidtg_postproc \
    libchromatix_csidtg_preview \
    libchromatix_csidtg_zsl_preview \
    libchromatix_s5k4h5yc_4k_preview_3a \
    libchromatix_s5k4h5yc_4k_video_3a \
    libchromatix_s5k4h5yc_common \
    libchromatix_s5k4h5yc_hfr_120_3a \
    libchromatix_s5k4h5yc_hfr_120_cpp \
    libchromatix_s5k4h5yc_hfr_120_isp \
    libchromatix_s5k4h5yc_liveshot_cpp \
    libchromatix_s5k4h5yc_liveshot_isp \
    libchromatix_s5k4h5yc_mode_effect_video_3a \
    libchromatix_s5k4h5yc_mode_hdr_auto_3a \
    libchromatix_s5k4h5yc_mode_hdr_auto_cpp \
    libchromatix_s5k4h5yc_mode_hdr_auto_isp \
    libchromatix_s5k4h5yc_mode_hdr_on_3a \
    libchromatix_s5k4h5yc_mode_hdr_on_cpp \
    libchromatix_s5k4h5yc_mode_hdr_on_isp \
    libchromatix_s5k4h5yc_mode_iso_cpp \
    libchromatix_s5k4h5yc_mode_iso_isp \
    libchromatix_s5k4h5yc_mode_lls_cpp \
    libchromatix_s5k4h5yc_mode_motion_lls_cpp \
    libchromatix_s5k4h5yc_mode_night_3a \
    libchromatix_s5k4h5yc_mode_night_cpp \
    libchromatix_s5k4h5yc_mode_night_isp \
    libchromatix_s5k4h5yc_mode_outfocus_3a \
    libchromatix_s5k4h5yc_mode_outfocus_cpp \
    libchromatix_s5k4h5yc_mode_outfocus_isp \
    libchromatix_s5k4h5yc_mode_panorama_3a \
    libchromatix_s5k4h5yc_mode_panorama_cpp \
    libchromatix_s5k4h5yc_mode_panorama_isp \
    libchromatix_s5k4h5yc_mode_sports_3a \
    libchromatix_s5k4h5yc_mode_sports_cpp \
    libchromatix_s5k4h5yc_mode_sports_isp \
    libchromatix_s5k4h5yc_preview_cpp \
    libchromatix_s5k4h5yc_preview_isp \
    libchromatix_s5k4h5yc_snapshot_cpp \
    libchromatix_s5k4h5yc_snapshot_isp \
    libchromatix_s5k4h5yc_sw_post_proc \
    libchromatix_s5k4h5yc_video_4k_cpp \
    libchromatix_s5k4h5yc_video_cpp \
    libchromatix_s5k4h5yc_video_isp \
    libchromatix_s5k4h5yc_vt_24fps_3a \
    libchromatix_s5k4h5yc_vt_30fps_3a \
    libchromatix_s5k4h5yc_zsl_preview_3a \
    libchromatix_s5k4h5yc_zsl_video_3a \
    libchromatix_s5k5e3yx_f2_2_common \
    libchromatix_s5k5e3yx_f2_2_hfr_120_3a \
    libchromatix_s5k5e3yx_f2_2_hfr_120_cpp \
    libchromatix_s5k5e3yx_f2_2_hfr_120_isp \
    libchromatix_s5k5e3yx_f2_2_liveshot_cpp \
    libchromatix_s5k5e3yx_f2_2_liveshot_isp \
    libchromatix_s5k5e3yx_f2_2_mode_effect_video_3a \
    libchromatix_s5k5e3yx_f2_2_mode_face_unlock_3a \
    libchromatix_s5k5e3yx_f2_2_mode_face_unlock_cpp \
    libchromatix_s5k5e3yx_f2_2_mode_face_unlock_isp \
    libchromatix_s5k5e3yx_f2_2_mode_hdr_auto_3a \
    libchromatix_s5k5e3yx_f2_2_mode_hdr_auto_cpp \
    libchromatix_s5k5e3yx_f2_2_mode_hdr_auto_isp \
    libchromatix_s5k5e3yx_f2_2_mode_hdr_on_3a \
    libchromatix_s5k5e3yx_f2_2_mode_hdr_on_cpp \
    libchromatix_s5k5e3yx_f2_2_mode_hdr_on_isp \
    libchromatix_s5k5e3yx_f2_2_preview_high_cpp \
    libchromatix_s5k5e3yx_f2_2_preview_high_isp \
    libchromatix_s5k5e3yx_f2_2_preview_low_cpp \
    libchromatix_s5k5e3yx_f2_2_preview_low_isp \
    libchromatix_s5k5e3yx_f2_2_snapshot_high_cpp \
    libchromatix_s5k5e3yx_f2_2_snapshot_high_isp \
    libchromatix_s5k5e3yx_f2_2_snapshot_high_lls_cpp \
    libchromatix_s5k5e3yx_f2_2_snapshot_low_cpp \
    libchromatix_s5k5e3yx_f2_2_snapshot_low_isp \
    libchromatix_s5k5e3yx_f2_2_sw_post_proc \
    libchromatix_s5k5e3yx_f2_2_video_high_cpp \
    libchromatix_s5k5e3yx_f2_2_video_high_isp \
    libchromatix_s5k5e3yx_f2_2_video_low_cpp \
    libchromatix_s5k5e3yx_f2_2_video_low_isp \
    libchromatix_s5k5e3yx_f2_2_vt_15fps_3a \
    libchromatix_s5k5e3yx_f2_2_vt_24fps_3a \
    libchromatix_s5k5e3yx_f2_2_vt_30fps_3a \
    libchromatix_s5k5e3yx_f2_2_vt_7fps_3a \
    libchromatix_s5k5e3yx_f2_2_vt_high_cpp \
    libchromatix_s5k5e3yx_f2_2_vt_high_isp \
    libchromatix_s5k5e3yx_f2_2_vt_low_cpp \
    libchromatix_s5k5e3yx_f2_2_vt_low_isp \
    libchromatix_s5k5e3yx_f2_2_zsl_preview_3a \
    libchromatix_s5k5e3yx_f2_2_zsl_video_3a \
    libcpion \
    libdeccfg \
    libdisplayconfig.qti \
    libdrmfs \
    libdsd2pcm \
    libflash_pmic \
    libhdcpsrm \
    libhifills \
    libhifills_interface \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libllvd_smore \
    libllvd_sw_tnr \
    libmm-hdcpmgr \
    libmm-qcamera \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_dcrf \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_modules \
    libmmcamera_chromaflash_lib \
    libmmcamera_dbg \
    libmmcamera_dcrf_lib \
    libmmcamera_dummyalgo \
    libmmcamera_dw9807_eeprom \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_interface \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_llvd \
    libmmcamera_lsi_s5k5e3yx_eeprom \
    libmmcamera_optizoom_lib \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_ppeiscore \
    libmmcamera_quadracfa \
    libmmcamera_s5k4h5yc \
    libmmcamera_s5k5e3yx \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_sw_tnr \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_trueportrait_lib \
    libmmcamera_ubifocus_lib \
    libmmjpeg \
    libmmjpeg_interface \
    libmmqjpeg_codec \
    libmmqjpegdma \
    liboemcrypto \
    libops \
    liboptizoom \
    libqcci_legacy \
    libqcmaputils \
    libqdma \
    libqmi_csi \
    libqomx_core \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libqrtr \
    libqsocket \
    libremosaic_daemon \
    libremosaiclib \
    libseemore \
    libsomp \
    libspl \
    libstagefright_soft_ac4dec \
    libstagefright_soft_ddpdec \
    libstr_capture_core \
    libstr_capture_interface \
    libstr_preview_core \
    libstr_preview_interface \
    libthermalioctl \
    libtrueportrait \
    libubifocus \
    libuniplugin \
    libvqzip \
    libwvaidl \
    libyasalgo \
    libswdap \
    libswgamedap \
    libswvqe \
    vendor.qti.hardware.alarm@1.0 \
    vendor.samsung.hardware.bluetooth@2.0 \
    vendor.samsung.hardware.gnss@2.0 \
    vendor.trustonic.tee@1.0 \
    vendor.trustonic.teeregistry@1.0 \
    audio.bluetooth_qti.default \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.0-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    libGPQTEEC_vendor \
    libQTEEConnector_vendor \
    libaoa \
    libbluetooth_audio_session_qti \
    libbtnv \
    libdlbdsservice \
    libminksocket \
    libsemnativecarrierfeature \
    vendor.dolby.hardware.dms@2.0-impl \
    vendor.qti.hardware.qteeconnector@1.0 \
    libadsp_hvx_add_constant \
    libadsp_hvx_skel \
    libadsp_hvx_stats \
    libadsp_hvx_zzhdr_BGGR \
    libadsp_hvx_zzhdr_RGGB \
    libapps_mem_heap \
    libdspCV_skel \
    libfastcvadsp \
    libfastcvadsp_skel \
    TimeService \
    android.hardware.drm-service.widevine.xml \
    android.hardware.gnss@2.0-service-qti.xml \
    manifest_vendor.dolby.hardware.dms.xml \
    vendor.qti.gnss@3.0-service.xml \
    adsprpcd \
    cdsprpcd \
    cnss-daemon \
    hvdcp_opti \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm-service.widevine \
    android.hardware.gnss@2.0-service-qti \
    android.hardware.sensors@1.0-service \
    mfgloader \
    vendor.display.color@1.0-service \
    vendor.dolby.hardware.dms@2.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.trustonic.tee@1.0-service \
    vendor.trustonic.teeregistry@1.0-service \
    init.qcom.sensors \
    init.qti.qseecomd \
    irsc_util \
    loc_launcher \
    lowi-server \
    mcDriverDaemon \
    mm-qcamera-app \
    mm-qcamera-daemon \
    mm-qjpeg-dec-test \
    mm-qjpeg-enc-test \
    mm-qomx-idec-test \
    mm-qomx-ienc-test \
    msm_irqbalance \
    pm-proxy \
    pm-service \
    qseecom_sample_client \
    qseecomd \
    rmt_storage \
    tftp_server \
    thermal-engine \
    time_client \
    time_daemon \
    vendor.qti.hardware.soter@1.0-provision \
    xtra-daemon

PRODUCT_PACKAGES += \
    vendor_lib_libEGL_adreno_so \
    vendor_lib_libGLESv2_adreno_so \
    vendor_lib64_libEGL_adreno_so \
    vendor_lib64_libGLESv2_adreno_so
